spin_manifest_version = 2

[application]
name = "sillydemo"
version = "0.0.1"
authors = ["Viktor Farcic <viktor@farcic.com>"]
description = "It's a silly demo"

[[trigger.http]]
route = "/..."
component = "sillydemo"

[component.sillydemo]
source = "main.wasm"
allowed_outbound_hosts = []

[component.sillydemo.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
